#!/usr/bin/env python3
"""Emit ib-sehs-lesson-data.js and prove every key matches a real section.

The failure mode this guards against is silent: if an authored key is spelled
differently from the section title in ib-sehs-native.js, the lesson still builds
(it falls back to the syllabus prose) but quietly loses its analogy and example.
So the section titles are read out of the live file and compared.
"""
import io, json, re, sys
import authored1, authored2, authored3, authored4

A = {}
A.update(authored1.A)
A.update(authored2.A)
A.update(authored3.A)
A.update(authored4.A)

# ── the real chapter-1 section titles, read from the shipped data file ──
nat = io.open('live-ib-sehs-native.js', encoding='utf-8').read()
data = io.open('live-ib-sehs-data.js', encoding='utf-8').read()

codes = re.findall(r"code:'([A-Z]\.\d\.\d)'", nat)
order, seen = [], set()
for c in codes:
    if c not in seen:
        seen.add(c); order.append(c)
ch1 = order                      # every topic, all three chapters
print('topic codes:', len(ch1))

# ns() headings in file order
titles = re.findall(r"ns\('((?:[^'\\]|\\.)*)'", nat)
# keep only headings whose enclosing topic is in chapter 1: walk the record list
# instead, because ns() also appears in other contexts.
recs = re.findall(r"\{code:'([A-Z]\.\d\.\d)',page:(\d+).*?sections:\[(.*?)\]\s*,\s*examFocus", nat, re.S)
real = []
for code, page, body in recs:
    if code in ch1:
        for t in re.findall(r"ns\('((?:[^'\\]|\\.)*)'", body):
            real.append((code, t))
print('sections found in native.js:', len(real))

missing = [t for _, t in real if t not in A]
extra = [k for k in A if k not in {t for _, t in real}]
if missing:
    print('\nMISSING authored entries:')
    for t in missing: print('   ', t)
if extra:
    print('\nAUTHORED BUT NOT A REAL SECTION:')
    for k in extra: print('   ', k)

out = ['/* IB SEHS focus lesson — authored layer.',
       '   One entry per section: the summary sentences, one analogy',
       '   (red card) and one example (blue card). Keys are the EXACT English',
       '   section titles used by IBSEHS_NATIVE / IB_DEEP / IB_VISUALS.',
       '   Generated by the build; edit authored*.py, not this.',
       '   Every **term** here also appears in that section\'s key-term list, so the',
       '   drill blanks a word the glossary will go on to define. */',
       'window.IBSEHS_LESSON = ' + json.dumps(A, ensure_ascii=False, indent=1).replace('\n', ' ') + ';']
src = '\n'.join(out) + '\n'
io.open('ib-sehs-lesson-data.js', 'w', encoding='utf-8').write(src)

stats = {'sections': len(A),
         'sentences': sum(len(v['sum']) for v in A.values()),
         'analogies': sum(1 for v in A.values() if v.get('analogy')),
         'examples': sum(1 for v in A.values() if v.get('example'))}
bolds = sum(len(re.findall(r'\*\*[^*]+\*\*', p['en']))
            for v in A.values() for p in v['sum'])
print('\nwrote ib-sehs-lesson-data.js  %d B' % len(src.encode()))
print(json.dumps(stats), '| **bold** spans in summaries:', bolds)
sys.exit(1 if (missing or extra) else 0)
