#!/usr/bin/env python3
"""Build course-hub.css from the approved ib-sehs-lesson.css.

Why generated and not hand-copied: every hand edit to a shared asset gets eaten
by the next rebase. This script is the single source, so the file can be
regenerated and diffed at any time.

What it does:
  * takes the READER + HUB half of ib-sehs-lesson.css (lines 23..1160 and
    2455..2486). The IB interactive-model half (1161..2454) is deliberately
    left out: those are .ns-* / .an-* / .kv-* drawings that only ib-sehs-models
    emits, and g10-bio has its own g10-* model layer.
  * renames the prefix: .ib- -> .ch-, ib-reading -> ch-reading, etc.
  * rebases the reader from a standalone PAGE to a full-screen OVERLAY, so the
    same reader can sit on top of a page that keeps its sidebar and top bar.
    That is the fix for the dead-end found on ib-sehs-learn.html, where the
    hub's "Start lesson" sets #lesson/<code> but the page has no reader shell.

Run from the repository root:
    python3 tools/mk-course-hub-css.py ib-sehs-lesson.css course-hub.css
and commit the regenerated course-hub.css with whatever changed upstream.
"""
import re
import sys

HEAD = """/* ═══════════════════════════════════════════════════════════════════════════
   course-hub.css — the Vitalité course layer: subject hub + lesson reader.

   GENERATED by tools/mk-course-hub-css.py from ib-sehs-lesson.css. Do not
   hand-edit this file; edit the generator and re-run it, or the next
   regeneration will silently drop the change.

   One engine, many courses. g10-bio.html and guide.html both build an outline
   from their own DOM and hand it to course-hub.js, which renders:

     #  / #progress        subject page: progress bar, START HERE, LEARN and
                           PRACTICE tiles, chapter > section tree with progress
     #topic/<code>       one section: status strip, tiles, its own content
     #defs/<code>        every key term in that section with its definition
     #lesson/<code>      the reader: one block at a time, bilingual, with a
                           progress bar, a section map, a live glossary and a
                           term-blanking drill

   The reader is a fixed overlay rather than a page of its own, so a course can
   keep its site chrome and its own URL. Everything is scoped under .ch-lesson
   so nothing here can reach the host page.
   ═══════════════════════════════════════════════════════════════════════════ */
"""

# The reader used to own <body class="ib-lesson"> on a chrome-free page. It is
# now the root of a fixed overlay, so every body-scoped rule becomes a plain
# class on that root. Ordered, because `body.ib-lesson` has to go before the
# bare `.ib-lesson` and both before the `.ib-` prefix rename.
BODY_RULES = [
    (r'body\.ib-lesson\b', '.ch-lesson'),
    (r'\.ib-lesson\b', '.ch-lesson'),
    (r'\.ib-reading\b', '.ch-reading'),
    (r'\.ib-resuming\b', '.ch-resuming'),
]

TOKENS = '''
/* ── the tokens ──────────────────────────────────────────────────────────────
   ib-sehs-lesson.css opens with a :root block holding the reader's own geometry
   tokens. It is part of the file, so it is part of the extraction.
   NB: these banners must be CSS comments. A bare `#` line is an ID SELECTOR, and
   the parser then swallows every following rule up to the next `}` — which is
   how the whole :root block silently stopped existing while the file still
   looked correct. */
:root {
  --rail-h: 58px;
  --rail-w: 296px;
  --lesson-w: 46rem;          /* comfortable measure for long-form reading */
  --r-sm: 8px;
  --r-md: 14px;
  --r-lg: 22px;
}

/* The theme does not name the scale this layer draws with. --line, --blue,
   --blue2 and --gold resolve to NOTHING on a page that never defined them, and
   a declaration containing an undefined var() is dropped outright — so 48
   border rules, 50 colour rules and 24 radius rules silently stop applying.
   No error, no warning: the hub just renders unbordered and its six-step
   progress scale loses four of its six colours.
   Every value below is taken from the site's OWN computed palette
   (--border2, --os-cobalt, --os-azure, --amber, --green, --red), so light and
   dark both come for free — those four already flip with body.dark.
   Measured on g10-bio: --line/--blue/--blue2/--gold were all empty, while
   --green #2E7D5B, --red #B3323A, --amber #B7791F, --os-cobalt #1E4F8F,
   --os-azure #3A78C2, --os-sky #8DB6E2 were present.
   Safe to define here: grep proves no other stylesheet on the site references
   any of these six names. */
:root {
  --line: var(--border2, rgba(22, 42, 74, .18));
  --blue: #1e4f8f;
  --blue2: #2f6fb5;
  --gold: var(--amber, #b7791f);
}

/* Dark needs its own blues. The theme's cobalt and azure are dark values: on
   #0D1829 they fall to ~3:1, which is why the dark override lifts them rather
   than reusing them. #5b93d6 and the theme's own --os-sky #8DB6E2 are tints of
   that same cobalt/azure and stay distinguishable, so the six-level scale keeps
   six colours instead of collapsing to two. */
body.dark {
  --blue: #5b93d6;
  --blue2: var(--os-sky, #8db6e2);
}

/* The status scale reads --green / --red. Both exist on this site today, but a
   page that did not define them would lose two more steps of the scale, so the
   fallbacks are stated once here. */
:root { --ch-green: var(--green, #2e7d5b); --ch-red: var(--red, #b3323a); }
'''

EXTRA = """
/* ═══ the overlay ═══════════════════════════════════════════════════════════
   The reader is a fixed layer over the host page. z-index sits below the
   tutorial spotlight's 2147483000+ layer so an onboarding bubble can still
   cover it if it ever fires, and above the site's FABs and notification bell. */
.ch-lesson {
  position: fixed;
  inset: 0;
  z-index: 2147482400;
  background: var(--bg);
  color: var(--text);
  overflow: auto;
  overscroll-behavior: contain;
  /* The host page must not scroll behind the reader. */
  -webkit-overflow-scrolling: touch;
}
body.ch-reading { overflow: hidden; }

/* the reading column clears the sticky footer */
.ch-lesson-shell { padding-bottom: 0; }
.ch-read { padding-bottom: 8rem; }

/* ═══ the course header (host page, above the hub) ═════════════════════════ */
.ch-course {
  max-width: 68rem;
  margin: 0 auto;
  padding: 1.4rem clamp(1rem, 3vw, 2rem) 0;
}
.ch-course__bar {
  display: flex; flex-wrap: wrap; align-items: flex-end;
  justify-content: space-between; gap: 1rem 1.4rem;
  padding-bottom: 1.1rem;
  border-bottom: 1px solid var(--line);
}
.ch-course__label {
  display: inline-flex; align-items: center; gap: .45rem;
  padding: .3rem .75rem; border-radius: 999px;
  background: color-mix(in srgb, var(--blue2) 11%, var(--surface));
  color: var(--blue2);
  font-size: .72rem; font-weight: 900;
  letter-spacing: .08em; text-transform: uppercase;
}
.ch-course__title {
  font-family: var(--font-heading);
  font-size: clamp(1.7rem, 4.4vw, 2.4rem);
  line-height: 1.12; letter-spacing: -.02em;
  margin: .7rem 0 0;
}
.ch-course__acts { display: flex; flex-wrap: wrap; gap: .5rem; }
.ch-course__btn {
  min-height: 44px; padding: .55rem 1.1rem;
  border: 1px solid var(--line); border-radius: 999px;
  background: var(--surface); color: var(--text);
  font-size: .9rem; font-weight: 800; cursor: pointer;
  display: inline-flex; align-items: center;
}
.ch-course__btn:hover { border-color: var(--text3); }
.ch-course__btn--primary {
  background: linear-gradient(180deg, #4a90e8, #3d7fd6);
  border-color: #3d7fd6; color: #fff;
  box-shadow: 0 2px 8px rgba(61, 127, 214, .3);
}

/* the overall progress bar under the course header */
.ch-overall {
  display: flex; align-items: center; gap: .8rem;
  margin-top: 1rem;
}
.ch-overall__bar {
  flex: 1 1 auto; height: 8px; border-radius: 999px;
  background: color-mix(in srgb, var(--text) 12%, transparent);
  overflow: hidden;
}
.ch-overall__fill {
  height: 100%; width: 0%; border-radius: 999px;
  background: linear-gradient(90deg, #4f8ff0, #6d5cf0);
  transition: width .32s cubic-bezier(.4, 0, .2, 1);
}
.ch-overall__n {
  flex: none; font-size: .82rem; font-weight: 900;
  color: var(--text2); font-variant-numeric: tabular-nums;
}
.ch-overall__t { flex: none; font-size: .8rem; color: var(--text3); }

/* The drawer is a full-height column of its own and the desktop version gets
   its horizontal inset from the shell's padding, which the fixed drawer does
   not have. Without this its labels sit flush against the screen edge. */
@media (max-width: 1039px) {
  .ch-lesson .ch-rail { padding-left: 1.15rem; padding-right: 1.15rem; }
  .ch-lesson .ch-rail__close { right: .5rem; top: .7rem; }
}

/* The block map's tick is drawn in CSS, not written as a glyph. vi-icons.js
   rewrites a whole-emoji text node inside a span into its own SVG, which gave
   every NOT-yet-reached block a coloured checkmark — the span's own
   `color: transparent` could not hide a replaced element. */
.ch-map__tick::after {
  content: ""; display: block;
  width: 5px; height: 9px; margin: -.16rem auto 0;
  border: solid currentColor; border-width: 0 2px 2px 0;
  transform: rotate(42deg);
}
.ch-map__tick { color: transparent; }
.ch-map__sec.is-done .ch-map__tick { color: #fff; }

/* The definitions toggle shipped at 38px, under the 40px floor every other
   control in this layer holds. */
button.ch-tile--toggle { min-height: 40px; }

/* The host page is always behind the reader, so the bar's 86% wash lets the
   site's own top bar read through it as a ghost. 94% keeps the frost and drops
   the ghost; the standalone reader had nothing behind it, which is why 86% was
   fine there. */
.ch-lesson .ch-top {
  background: color-mix(in srgb, var(--bg) 94%, transparent);
}

/* ═══ the host page's own content while the hub is up ══════════════════════ */
.ch-pagebody[hidden] { display: none !important; }

/* ═══ reader blocks lifted straight out of a course page ══════════════════
   A course page keeps its prose, tables and figures in ordinary elements, so a
   "block" here is a clone of those elements rather than something this file
   knows how to draw. The rules below give them a reading measure and let the
   page's own table/callout styling do the rest. */
.ch-blocks { min-width: 0; }
.ch-blocks > * { max-width: 68ch; }
.ch-blocks > .table-wrap,
.ch-blocks > table,
.ch-blocks > figure,
.ch-blocks > img { max-width: 100%; }
.ch-blocks > img { display: block; height: auto; border-radius: var(--r-md); }
.ch-blocks h4, .ch-blocks h3 { margin: 1.5rem 0 .5rem; }
.ch-blocks > h4:first-child, .ch-blocks > h3:first-child { margin-top: 0; }
.ch-blocks .ch-empty { color: var(--text3); }

/* The reveal: a new block arrives, everything older steps back. Both states are
   on the block itself, so Back restores the previous emphasis exactly. */
@keyframes ch-in { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: none; } }
.ch-read > .ch-block.is-in { animation: ch-in .3s cubic-bezier(.4, 0, .2, 1) both; }
@media (prefers-reduced-motion: reduce) {
  .ch-read > .ch-block.is-in { animation: none; }
}

/* the reader reuses the page's own tables, which are built for a wide column */
.ch-blocks .table-wrap { margin: 1.2rem 0; }
.ch-blocks table { margin: 0; }

/* a section's own heading inside the reader */
.ch-sec__title {
  font-family: var(--font-heading);
  font-size: 1.25rem; line-height: 1.25;
  margin: 0 0 .8rem;
}

/* the topic page's copy of the section lives here */
.ch-guide .ch-blocks { max-width: none; }
.ch-guide .ch-blocks > * { max-width: 68ch; }
"""


def main():
    src_path, out_path = sys.argv[1], sys.argv[2]
    lines = open(src_path, encoding='utf-8').read().split('\n')
    # 1-indexed inclusive ranges, verified against the section banners in the
    # source file. Asserted here so a re-download of the source cannot silently
    # shift them.
    def grab(a, b):
        return '\n'.join(lines[a - 1:b])

    assert '--rail-h' in grab(13, 21), grab(13, 21)

    # The ranges are FOUND BY THEIR BANNER COMMENTS, never hardcoded. They were
    # hardcoded once and a 3KB addition upstream moved every banner below it —
    # the reader block alone slid 2455 -> 2546 — so the extraction silently
    # grabbed the wrong lines while the file still looked plausible.
    def at(needle, nth=0):
        hits = [i for i, l in enumerate(lines) if needle in l]
        assert len(hits) > nth, 'banner not found: %r (%d hits)' % (needle, len(hits))
        return hits[nth]

    BASE      = at('/* ── base ')
    TOK       = at('--rail-h')                     # the geometry token block
    FIGTAB    = at('/* ── figures and tables ')
    FLASH     = at('/* ── flashcard slide ')
    GENFIG    = at('/* ── generated figures ')
    RECEDE    = at('/* ── recede ')
    TAPTGT    = at('/* ── tap targets inside the study guide ')
    FOCUSED   = at('/* ═══ reader as a focused player')
    MODELS    = at('/* ═══ IB SEHS interactive models')
    print('  banners at: base=%d tokens=%d figtab=%d flash=%d genfig=%d recede=%d '
          'taptgt=%d focused=%d models=%d'
          % (BASE + 1, TOK + 1, FIGTAB + 1, FLASH + 1, GENFIG + 1,
             RECEDE + 1, TAPTGT + 1, FOCUSED + 1, MODELS + 1))
    assert TOK < BASE < FIGTAB < FLASH < GENFIG < RECEDE < TAPTGT < FOCUSED, \
        'the banners are not in the order this extraction assumes'

    # Two blocks are IB-only and are dropped on purpose:
    #   "figures and tables"   .ib-fig / .ib-tbl, the reader's own figure and
    #                          table slide renderers. This engine clones the
    #                          course page's real tables instead, so dead.
    #   "generated figures"    the .plate / .lblL / .solid rules that
    #                          ib-sehs-visuals.js draws with. g10 has no .vis-svg.
    # Both reference var(--border) and var(--accent). Those names are UNDEFINED
    # on this site (measured: 76 uses in g10-bio.html, 61 in the theme, all
    # currently inert), and the source file's own `:root{--border:var(--line)}`
    # alias would define them — activating 200+ dormant declarations across the
    # whole site in one move. So the alias goes too and the output is asserted
    # to contain neither name.
    body = grab(BASE, FIGTAB) + grab(FLASH, GENFIG) + grab(RECEDE, TAPTGT)
    # Drop the source's own `--border: var(--line)` alias for the reason above,
    # and repoint the blocks that USED those two names. On the IB page --border
    # was defined as --line and --accent as --gold, so a use of either there is
    # exactly a use of the pair defined here; rewriting the reference keeps those
    # rules correct without ever DEFINING the two names, which is the only thing
    # with a site-wide blast radius. (Upstream added .native-deep, .ib-missing,
    # .ib-defgrp and .ib-tile--toggle after the file this extraction was first
    # written against, and all four name --border.)
    alias = ':root { --border: var(--line); --accent: var(--gold); }'
    assert body.count(alias) == 1, body.count(alias)
    body = body.replace(alias, '')
    body = body.replace('var(--border)', 'var(--line)')
    body = body.replace('var(--accent)', 'var(--gold)')
    # the tail runs to the end of the file; the focused-player block is last
    # (bounded by the IB model CSS that was appended upstream after it)
    END = MODELS if MODELS > FOCUSED else len(lines)
    tail = grab(FOCUSED, END)
    print('  tail = lines %d..%d' % (FOCUSED + 1, END))
    assert 'foot__btn--next' in tail, tail[-400:]
    assert 'IB SEHS interactive models' not in tail, 'the model CSS leaked back in'
    # and it must not drag the IB model layer in from ABOVE
    assert MODELS > TAPTGT, 'model CSS sits before the tap-target block'

    out = body + '\n' + tail + '\n'

    # ORDER MATTERS: the body-scoped rules have to lose their `body.` prefix
    # BEFORE the bare `.ib-` -> `.ch-` rename, or the pattern no longer matches
    # and every one of them silently stays dead (body.ch-lesson never exists).
    for pat, rep in BODY_RULES:
        out = re.sub(pat, rep, out)

    # the six-level scale's two colours go through the guarded pair
    out = out.replace('var(--green)', 'var(--ch-green)').replace('var(--red)', 'var(--ch-red)')

    # rename the prefix
    out = out.replace('.ib-', '.ch-')
    out = out.replace('--ib-c-', '--ch-c-')
    out = out.replace('#ibReader', '#chReader').replace('#ibRead', '#chRead')
    out = out.replace('#ibFoot', '#chFoot').replace('#ibRailToggle', '#chRailToggle')
    out = out.replace('#ibBack', '#chBack').replace('#ibNext', '#chNext')
    out = out.replace('#ibFill', '#chFill').replace('#ibCount', '#chCount')
    out = out.replace('#ibDrill', '#chDrill').replace('#ibExit', '#chExit')
    out = out.replace('#ibLang', '#chLang').replace('#ibDark', '#chDark')
    out = out.replace('#ibScrim', '#chScrim').replace('#ibMap', '#chMap')
    out = out.replace('#ibGloss', '#chGloss').replace('#ibRailClose', '#chRailClose')
    out = out.replace('#ibRailHub', '#chRailHub')

    # The drawer close button: the base `.ch-rail__close{display:none}` sits
    # AFTER the max-width:1039px rule that enables it, at the same specificity,
    # so source order won and the button never rendered on a phone. The source
    # file's own comment describes this bug and then still ships it. Qualifying
    # the in-query selector raises it to (0,2,0) and wins on specificity.
    assert out.count('  .ch-rail__close { display: inline-flex; }') == 1
    out = out.replace('  .ch-rail__close { display: inline-flex; }',
                      '  .ch-lesson .ch-rail__close { display: inline-flex; }')


    out = HEAD + out + TOKENS + EXTRA
    open(out_path, 'w', encoding='utf-8').write(out)

    # post-conditions: no `ib-` may survive, and the two halves must be there.
    txt = open(out_path, encoding='utf-8').read()
    leftover = [l for l in txt.split('\n')
                if 'ib-' in l and 'ib-sehs-lesson.css' not in l]
    assert not leftover, leftover[:6]
    # The whole reason the two dead blocks are dropped: defining --border or
    # --accent here would switch on every `var(--border)` in the site at once.
    # Defining these two at :root would switch on every `var(--border)` in the
    # site at once — 76 dormant uses in g10-bio.html alone, 61 in the theme.
    # A *reference* is fine (rewritten above); a *definition* is not.
    for banned in ['--border:', '--accent:', '.vis-svg']:
        hits = [l for l in txt.split('\n') if banned in l]
        assert not hits, (banned, hits[:4])
    for must in ['--rail-h: 58px', '--r-md: 14px', '--line: var(--border2',
                 '--blue2: #2f6fb5', 'body.dark {', '--ch-green:',
                 '.ch-lesson {', '.ch-hub {', '.ch-tabs {', '.ch-lev {',
                 '.ch-rtile {', '.ch-trow {', '.ch-defcard {', '.ch-blank {',
                 '.ch-foot {', '.ch-top {', '.ch-rail {', '.ch-course {']:
        assert must in txt, must
    print('%s  %d bytes  %d lines' % (out_path, len(txt.encode()), txt.count('\n') + 1))


if __name__ == '__main__':
    main()